function results = run_sensitivity_analysis(time_ode, T_ode, X0_state, juveniles, adult_fems, thresh)

% Input: - time_ode (array): monthly time grid for ODE integration [months]
%     - T_ode (array): temperature time series over time_ode [°C]
%     - X0_state (list of float): initial state [J0; A0] [#crabs/1000m²]
%     - juveniles (array): observed juvenile densities [#crabs/1000m²]
%     - adult_fems (array): observed adult female densities [#crabs/1000m²]
%     - thresh (float): threshold fraction of max(mu) used to draw the significance cutoff line in plots
% 
% Output: - results (struct) with keys: - thresh (float): significance threshold as provided in input
%                                       - X_labels (cell array of str): parameter names ['p', 'x', 'alpha', 'b', 'm', 'beta_RR', 'r_T', 'f_l']
%                                       - M (int): number of parameters (8)
%                                       - lb (array): lower bounds of the parameter space
%                                       - ub (array): upper bounds of the parameter space
%                                       - sens_analysis_elapsed_time (float): computation time [secods]
%                                       - mi_J, mi_A (array): mean of Elementary Effects mi for juveniles and adults
%                                       - sigma_J, sigma_A (array): standard deviation of Elementary Effects sigma for juveniles and adults
%                                       - mi_boot_J, mi_boot_A (array): bootstrapped mu values for juveniles and adults
%                                       - sigma_boot_J, sigma_boot_A (array): bootstrapped sigma values for juveniles and adults
%                                       - mi_sd_J, mi_sd_A (array): standard deviation of bootstrapped mu for juveniles and adults
%                                       - sigma_sd_J, sigma_sd_A (array): standard deviation of bootstrapped sigma for juveniles and adults
%                                       - mi_lb_J, mi_ub_J, mi_lb_A, mi_ub_A (array): bootstrap lower and upper confidence bounds on mu for juveniles and adults
%                                       - sigma_lb_J, sigma_ub_J, sigma_lb_A, sigma_ub_A (array): bootstrap lower and upper confidence bounds on sigma for juveniles and adults
%                                       - rr (array): sample sizes used for convergence analysis
%                                       - m_r_J, m_r_A (array): mu convergence values at each sample size, for juveniles and adults
%                                       - m_r_boot_J, m_r_boot_A (array): bootstrapped mu convergence values for juveniles and adults
%                                       - s_r_J, s_r_A (array): standard deviation of mu convergence for juveniles and adults
%                                       - m_lb_r_J, m_ub_r_J, m_lb_r_A, m_ub_r_A (array): bootstrap lower and upper confidence bounds on mu convergence for juveniles and adults
%                                       - Y_J, Y_A (array, shape (n_samples,)): MSE values on juveniles and adults across all sampled parameter sets
% 
% Performs global sensitivity analysis using the Elementary Effects (Morris) method via SAFEpython. Samples 1000 parameter sets with LHS in a radial design, runs the model, and computes μ and σ indices for both juveniles and adults. 
% Includes bootstrapping (Nboot=100) for confidence intervals and convergence analysis over 5 sample sizes.
   
p0 = [30.62/12; 0.01256; 0.9/12; 1; 1/15.7; 0.294/12];
X0 = [60; 5; p0];
X_labels = {'p','x','\alpha','b','m','\beta_{RR}','r_T','f_l'};
% bounds
lb = [10/X0(1); 1.01/X0(2); 0.2*ones(length(p0),1)];
ub = [1; 1; 1.8*ones(length(p0),1)];

% inputs:
DistrFun = 'unif'; % parameter distribution

M = size(lb,1); % number of inputs ( = parameters)
DistrPar = cell(M,1); 
for i=1:M; DistrPar{i} = [lb(i) ub(i)] ; end

%% sample inputs space

SampStrategy = 'lhs' ; % Latin Hypercube -> input space unuformely sampled
r = 100 ; % Number of samples
design_type ='radial'; % other option is 'trajectory'
X = OAT_sampling(r,M,DistrFun,DistrPar,SampStrategy,design_type);
X = X.*X0';

%% run model
tic
[Y, ~] = model_eval(X, time_ode, T_ode, X0_state, juveniles, adult_fems);
Y_J = Y(:,1); % juveniles
Y_A = Y(:,2); % adults

%% elementary effects computation                    

% Compute Elementary Effects:                                                  
[mi_J, sigma_J] = EET_indices(r,lb',ub',X,Y_J,design_type); 
[mi_A, sigma_A] = EET_indices(r,lb',ub',X,Y_A,design_type); 

% Use bootstrapping to derive confidence bounds:                               
Nboot = 100;                                                                     
[mi_boot_J,sigma_boot_J,EE_J,mi_sd_J,sigma_sd_J,mi_lb_J,sigma_lb_J,mi_ub_J,sigma_ub_J] = ...               
EET_indices(r,lb',ub',X,Y_J,design_type,Nboot);   
[mi_boot_A,sigma_boot_A,EE_A,mi_sd_A,sigma_sd_A,mi_lb_A,sigma_lb_A,mi_ub_A,sigma_ub_A] = ...               
EET_indices(r,lb',ub',X,Y_A,design_type,Nboot);

% convergence
rr = [ r/5:r/5:r ] ;                                                           
m_r_J = EET_convergence(EE_J,rr);  
m_r_A = EET_convergence(EE_A,rr);

% convergence with bootstrapping                                                                  
rr = [ r/5:r/5:r ] ;                                                           
[m_r_boot_J,s_r_J,m_lb_r_J,m_ub_r_J] = EET_convergence(EE_J,rr,Nboot); 
[m_r_boot_A,s_r_A,m_lb_r_A,m_ub_r_A] = EET_convergence(EE_A,rr,Nboot); 

sens_analysis_elapsed_time = toc;

disp('sensitivity analysis elapsed time = '+ string(sens_analysis_elapsed_time) + ' s')
%% pack results
results = struct(thresh=thresh,...
         M=M,...
         ub=ub,...
         lb=lb,...
         sens_analysis_elapsed_time=sens_analysis_elapsed_time,...
         mi_J=mi_J,...
         sigma_J=sigma_J,...
         mi_A=mi_A,...
         sigma_A=sigma_A,...
         rr=rr,...
         m_r_J=m_r_J,...
         m_r_A=m_r_A,...
         mi_boot_J=mi_boot_J,...
         sigma_boot_J=sigma_boot_J,...
         mi_boot_A=mi_boot_A,...
         sigma_boot_A=sigma_boot_A,...
         m_r_boot_J=m_r_boot_J,...
         m_r_boot_A=m_r_boot_A,...
         mi_sd_J=mi_sd_J,...
         sigma_sd_J=sigma_sd_J,...
         mi_lb_J=mi_lb_J,...
         mi_ub_J=mi_ub_J,...
         sigma_lb_J=sigma_lb_J,...
         sigma_ub_J=sigma_ub_J,...
         mi_sd_A=mi_sd_A,...
         sigma_sd_A=sigma_sd_A,...
         mi_lb_A=mi_lb_A,...
         mi_ub_A=mi_ub_A,...
         sigma_lb_A=sigma_lb_A,...
         sigma_ub_A=sigma_ub_A,...
         m_lb_r_J=m_lb_r_J,...
         m_ub_r_J=m_ub_r_J,...
         s_r_J=s_r_J,...
         m_lb_r_A=m_lb_r_A,...
         m_ub_r_A=m_ub_r_A,...
         s_r_A=s_r_A,...
         Y_J = Y_J,...
         Y_A = Y_A);
end

